---
title: Temperature log
hero_image: images/banner.png
description: Measure the temperature with your Raspberry Pi, and log the data
original_url: https://raspberrypi.org/learning/temperature-log
theme: turquoise
duration: 2
listed: false
ingredient: false
copyedit: true
curriculum: 3, design-0, programming-3, phys-comp-1, manufacture-0, community-0
interests: science
technologies: raspberry-pi, electronic-components, python
site_areas: projects
hardware: raspberry-pi, electronic-components
software: python
version: 4
last_tested: 2019-09-17
steps:
- title: Introduction
- title: Creating a Python script to monitor temperature
- title: Writing the data to a CSV file
  completion:
  - engaged
- title: Live-graphing the data
- title: Automating the script
  completion:
  - internal
- title: What next?
